# Example RoadRunner configuration with Sentry Transport plugin

version: "3"

# RoadRunner configuration
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php app.php"
  user: ""
  group: ""
  env:
    - GOMAXPROCS: 2
  relay: "pipes"
  relay_timeout: "20s"

# Sentry Transport Plugin Configuration
sentry_transport:
  # Enable/disable the plugin
  enabled: true
  
  # Sentry DSN (replace with your actual DSN)
  dsn: "https://your-public-key@sentry.io/your-project-id"
  
  # HTTP transport settings
  transport:
    # Request timeout
    timeout: "30s"
    # Connection timeout
    connect_timeout: "10s"
    # Enable gzip compression
    compression: true
    # SSL verification
    ssl_verify: true
    # Proxy settings (optional)
    # proxy: "http://proxy.example.com:8080"
    # proxy_auth: "username:password"
  
  # Retry configuration
  retry:
    # Maximum retry attempts
    max_attempts: 3
    # Initial backoff duration
    initial_backoff: "1s"
    # Backoff multiplier
    backoff_multiplier: 2
    # Maximum backoff duration
    max_backoff: "300s"
    # Enable dead letter queue
    dead_letter_queue: true
  
  # Queue configuration
  queue:
    # Buffer size for the event queue
    buffer_size: 1000
    # Number of worker goroutines
    workers: 4
    # Batch size for processing events
    batch_size: 10
    # Batch timeout
    batch_timeout: "5s"
  
  # Logging configuration
  logging:
    # Log level for plugin operations
    level: "info"

# HTTP Plugin (if needed)
http:
  address: "0.0.0.0:8080"
  middleware: []
  uploads:
    forbid: [".php", ".exe", ".bat"]
  trusted_subnets:
    - "10.0.0.0/8"
    - "127.0.0.0/8"
    - "172.16.0.0/12"
    - "192.168.0.0/16"
    - "::1/128"
    - "fc00::/7"
    - "fe80::/10"

# Logger configuration
logs:
  mode: "production"
  level: "info"
  encoding: "json"
  output: "stderr"
  error_output: "stderr"

# Endure container configuration
endure:
  grace_period: "30s"
  print_graph: false
  log_level: "info"
